### ISSUE TITLE
Erlaubter Ladestrom mqtt

### ISSUE THREAD

**Issue by fr-Fabix** [Tinkerforge/warp-charger#32]
Hallo!

Ich habe die WARP1 mit 2.1.2 im Einsatz mit mqtt über homeassistant.

Ich versuche den Ladestrom zu setzen. Dabei gibt es folgendes Phänomen:

1. Ladestrom wird übernommen
2. Einige Sekunden später ist der Ladestrom 0

Siehe Video

https://user-images.githubusercontent.com/107420972/232071942-222ada05-1b98-4d68-8555-4f418a335187.mov

**Comment by MattiasTF** [comment]
Kann ich leider nicht reproduzieren. Kannst du dich mal mit mosquitto_sub oder etwas ähnlichem auf das MQTT-Topic `warp/USH/evse/external_current` subscriben, um zu testen, ob die 0-Updates per MQTT kommen?

Hast du ansonsten zufällig EVCC oder sowas im Einsatz? EVCC setzt nämlich genau den gleichen Wert.

Falls das dein Problem noch nicht löst, poste mal ein Debug-Log.

**Comment by fr-Fabix** [comment]
> Kann ich leider nicht reproduzieren. Kannst du dich mal mit mosquitto_sub oder etwas ähnlichem auf das MQTT-Topic `warp/USH/evse/external_current` subscriben, um zu testen, ob die 0-Updates per MQTT kommen?
> 
> Hast du ansonsten zufällig EVCC oder sowas im Einsatz? EVCC setzt nämlich genau den gleichen Wert.
> 
> Falls das dein Problem noch nicht löst, poste mal ein Debug-Log.

Du hast recht! Ich hatte testweise evcc laufen.... 

Danke!

**Comment by rediculum** [comment]
@fr-Fabix wie hast du es jetzt gelöst, dass du HA und evcc zusammen kombinieren konntest? die HA integration in warp2 setzt den Ladestrom ja über ```external_current```. Wäre es nicht besser, diesen über ```global_current``` zu setzen, denn bei mir funktioniert das nur so.

**Comment by MattiasTF** [comment]
> Wäre es nicht besser, diesen über `global_current` zu setzen, denn bei mir funktioniert das nur so.

Der Wert für `global_current` wird im Flash-Speicher des EVSE gespeichert. Wenn du den automatisiert setzen lässt, ist der Flash in absehbarer Zeit hinüber. Davon rate ich ab.

`external_current` wird nur im RAM gehalten und ist für eine externe, automatisierte Steuerung vorgesehen, die den Wert beliebig oft ändern kann.

**Comment by rediculum** [comment]
Wenn es um Überschussladen geht verstehe ich das, weil sich der Ladestrom dauernd ändern kann (Wolke zieht z.b. rüber), aber wenn ich "fast" laden will und nicht die vollen 16A möchte, setze ich das jetzt über ```global_current```, anders geht nicht. Aber auch bei PV Laden kommt es manchmal vor, dass ich nur bis max. 8A laden will, weil meine Huawei Batterie max 5KW Durchsatz hat und sonst vom Netz bezogen wird, was ja nicht im Interesse ist. Dann setze das auch über ```global_current```. Vielleicht mach ich da ein Anwendungsfehler?

**Comment by MattiasTF** [comment]
In dem Fall ist `global_current` tatsächlich eine sinnvolle Möglichkeit. Wenn du das nur gelegentlich setzt und nicht mittels einer Regelung, die den Wert live anpasst, schadet das nicht. `external_current` wäre zwar prinzipiell besser, aber wenn HomeAssistant das schon an anderer setzt, kannst du das nicht überschreiben.

**Comment by rediculum** [comment]
Zur Ergänzung und Doku, hier das zusätziche HA Entity für den (global) Ladestrom.
Wie bereits von TF gewarnt, **NICHT FÜR DYNAMISCHEN LADESTROM VERWENDEN** (z.B. eigenes PV Überschussladen Script)

```
- number:
    unique_id: warp2-global_current
    default_entity_id: warp2-global_current
    command_topic: 'warp2/evse/global_current_update'
    state_topic: 'warp2/evse/global_current'
    command_template: '{{ value * 1000 }}'
    value_template: '{{ (value_json.current | float / 1000) | round(3) }}'
    unit_of_measurement: A
    max: 16
    min: 6
    name: Ladestrom
    device:
      identifiers: warp2
      manufacturer: Tinkerforge GmbH
      model: WARP2 Charger
      name: WARP2 Charger (warp2)
```
